name: Starknet-P2p-Specs-CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled
      - edited

env:
  PROTOC_VERSION: v25.1

jobs:
  compile-protos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - uses: Noelware/setup-protoc@1.1.0
        with:
          version: ${{env.PROTOC_VERSION}}

      # - name: Install protobuf compiler (protoc)
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y protobuf-compiler

      - name: protoc version
        run: protoc --version

      - name: Validate .proto files for Rust compatibility
        run: |
          protoc --rust_out=/dev/null ./p2p/proto/*.proto
          protoc --rust_out=/dev/null ./p2p/proto/**/*.proto
      
      - name: Validate .proto files for Java compatibility
        run: |
          protoc --java_out=/dev/null ./p2p/proto/*.proto
          protoc --java_out=/dev/null ./p2p/proto/**/*.proto

      - name: Validate .proto files for Python compatibility
        run: |
          protoc --python_out=/dev/null ./p2p/proto/*.proto
          protoc --python_out=/dev/null ./p2p/proto/**/*.proto

      - name: Validate .proto files for C++ compatibility
        run: |
          protoc --cpp_out=/dev/null ./p2p/proto/*.proto
          protoc --cpp_out=/dev/null ./p2p/proto/**/*.proto

      - name: Validate .proto files for Go compatibility
        run: |
          protoc --go_out=/dev/null ./p2p/proto/*.proto
          protoc --go_out=/dev/null ./p2p/proto/**/*.proto

      - name: Success Message
        run: echo "All proto compilations passed!"
